QuickEvents.Website.WebApp/ViewModels/LoginForm.cs
using System.ComponentModel.DataAnnotations;

namespace QuickEvents.Website.WebApp.ViewModels
{
    public class LoginForm
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [RegularExpression(@"(([\w-\.]+)@([\w-\.]+)\.([\w-\.]+))")]
        public string Email { get; set; }
    }
}

QuickEvents.Website.WebApp/ViewModels/RegisterForm.cs
using System.ComponentModel.DataAnnotations;

namespace QuickEvents.Website.WebApp.ViewModels
{
    public class RegisterForm
    {
        [Required]
        public string NewUserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }
        [Compare("NewPassword")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [Required]
        [RegularExpression(@"(([\w-\.]+)@([\w-\.]+)\.([\w-\.]+))")]
        public string NewEmail { get; set; }

        public bool IsFromFreeTrial { get; set; }
    }
}

QuickEvents.Website.WebApp/Controllers/EventController.cs
using QuickEvents.Website.WebApp.Model.Models;
using QuickEvents.Website.WebApp.Service.Services;
using QuickEvents.Website.WebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using QuickEvents.Website.WebApp.Helpers;

namespace QuickEvents.Website.WebApp.Controllers
{
    [RoutePrefix("event")]
    public class EventController : Controller
    {
        [Route("")]
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var userCookie = Request.Cookies["User"];
            var events = new List<Event>();

            if (userCookie != null)
            {
                events = await new EventService().GetByUserId(Convert.ToInt32(userCookie.Values["UserId"]));
            }

            return View(events);
        }

        [Route("add")]
        [HttpGet]
        [Authorize]
        public ActionResult Add()
        {
            return View(new EventUploadForm { StartDate = null, EndDate = null });
        }

        [Route("preview")]
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Preview(EventUploadForm eventUploadForm)
        {
            if (ModelState.IsValid)
            {
                if (await new EventService().CheckAvailability(eventUploadForm.EventID))
                {
                    return PartialView("_Preview", eventUploadForm);
                }
                ModelState.AddModelError("EventID", "This EventID is already taken");
            }
            Response.StatusCode = 422;
            return PartialView("_UploadForm", eventUploadForm);

        }

        [Route("upload")]
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Upload(EventUploadForm eventUploadForm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var myEvent = eventUploadForm.ConvertEventUploadFormToEvent();
                    myEvent.UserID = Convert.ToInt32(Request.Cookies["User"].Values["UserId"]);
                    myEvent = await new EventService().Add(myEvent);
                    if (myEvent != null)
                    {
                        Response.StatusCode= 202;
                        return null;
                    }

                    Response.StatusCode = 400;
                    return null;
                }
                catch (Exception ex)
                {
                    Response.StatusCode = 400;
                    return null;
                }
            }
            return null;
        }
    }
}

QuickEvents.Website.WebApp/Controllers/UserController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using QuickEvents.Website.WebApp.Model.Models;
using QuickEvents.Website.WebApp.Models;
using QuickEvents.Website.WebApp.Service.Services;
using QuickEvents.Website.WebApp.ViewModels;

namespace QuickEvents.Website.WebApp.Controllers
{
    [RoutePrefix("user")]
    public class UserController : Controller
    {
        [Route]
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            return View();

        }

        [Route("login")]
        public ActionResult Login()
        {
            return PartialView("_Login", new LoginForm());
        }

        [Route("login")]
        [HttpPost]
        public async Task<ActionResult> Login(LoginForm loginForm)
        {
            if (!ModelState.IsValid) return null;

            try
            {
                var user = new QuicEventUser
                {
                    Username = loginForm.UserName,
                    Password = loginForm.Password,
                    EmailAddress = loginForm.Email
                };

                user = await new UserService().GetUser(user);
                if (null != user)
                {
                    FormsAuthentication.SetAuthCookie(loginForm.UserName, false);
                    var userCookie = new HttpCookie("User");
                    userCookie.Values.Add("UserId", $"{user.Id}");
                    Response.Cookies.Add(userCookie);
                    return null;
                }
                FormsAuthentication.SignOut();
                Response.StatusCode = 422;
                ModelState.AddModelError("", "Username or Password is wrong");
                return PartialView("_Login", loginForm);
            }
            catch (Exception ex)
            {

            }

            return null;
        }

        [Route("signout")]
        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [Route("register")]
        public ActionResult Register()
        {
            return PartialView("_RegisterForm", new RegisterForm { IsFromFreeTrial = true });
        }

        [Route("register")]
        [HttpPost]
        public async Task<ActionResult> Register(RegisterForm registerForm)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var isUsernameFree = await new UserService().CheckAvailability(registerForm.NewUserName);
                    if (isUsernameFree) {
                        var newUser = new QuicEventUser
                        {
                            Username = registerForm.NewUserName,
                            Password = registerForm.NewPassword,
                            EmailAddress = registerForm.NewEmail
                        };

                        newUser = await new UserService().Add(newUser);

                        FormsAuthentication.SetAuthCookie(newUser.Username, false);
                        var userCookie = new HttpCookie("User");
                        userCookie.Values.Add("UserId", $"{newUser.Id}");
                        Response.Cookies.Add(userCookie);
                        return null;
                    }

                    ModelState.AddModelError("NewUserName", "Username already exists.");
                    Response.StatusCode = 422;
                    return PartialView("_RegisterForm", registerForm);

                }
                catch (Exception ex)
                {
                    Response.StatusCode = 400;
                    return null;
                }
            }

            Response.StatusCode = 422;
            return PartialView("_RegisterForm", registerForm);

        }
    }
}

QuickEvents.Website.WebApp/Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h2>Logged in bro!</h2>

QuickEvents.Website.WebApp/Views/User/_Login.cshtml
@using QuickEvents.Website.WebApp.ViewModels
@model LoginForm

<div class="modal-body">
    <form id="LoginForm">
        @Html.ValidationSummary()
        <table class="table">
            <tbody>
            <tr class="form-group">
                <td> @Html.TextBoxFor(x => x.UserName, new { @class = "form-control", @placeholder = "Enter Username" })</td>
            </tr>
            <tr class="form-group">
                <td> @Html.TextBoxFor(x => x.Password, new { @class = "form-control", @placeholder = "Enter Password", @type = "password" })</td>
            </tr>
            <tr>
                <td><a id="NewUserBtn" class="fakeButton">New User</a></td>
            </tr>
            <tr>
                <td><a id="ForgotPasswordBtn" class="fakeButton">Forgot Password?</a></td>
            </tr>
            </tbody>
        </table>

        <div class="modal-footer">
            <div class="btn-group btn-group-lg">
                <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-success">Sign in</button>
            </div>
        </div>
    </form>

    @Html.Partial("_RegisterForm", new RegisterForm())
    
    <form id="ForgotPasswordForm" class="hidden">
        @Html.ValidationSummary()
        <table class="table">
            <tbody>
            <tr class="form-group">
                <td> @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @placeholder = "Enter Email" })</td>
            </tr>
            </tbody>
        </table>

        <div class="modal-footer">
            <div class="btn-group btn-group-lg">
                <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-success">Save</button>
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    $("#SignupForm").addClass("hidden");

    $("#NewUserBtn").on('click', function(e) {
        e.preventDefault();

        $("#LoginForm").addClass("hidden");
        $("#SignupForm").removeClass("hidden");
    });

    $("#ForgotPasswordBtn").on('click', function (e) {
        e.preventDefault();

        $("#LoginForm").addClass("hidden");
        $("#ForgotPasswordForm").removeClass("hidden");
    });

    $("#LoginForm").on('submit', function (e) {
        SetLoadingDiv(true);

        e.preventDefault();
        $.ajax({
            url: "@Url.Action("Login")",
            method: "POST",
            data: $("#LoginForm").serialize(),
            success: function () {
               location.href = "@Url.Action("Index", "Event")";
            },
            error: function (response) {
                SetLoadingDiv(false);
                $(".modal-body").html(response.responseText);
            }

        });
    });
</script>

QuickEvents.Website.WebApp/Views/User/_RegisterForm.cshtml
@model QuickEvents.Website.WebApp.ViewModels.RegisterForm
@{
    var divClass = Model.IsFromFreeTrial ? "modal-body" : "";
}

<div class="@divClass">
    <form id="SignupForm">
        @Html.ValidationSummary()
        <table class="table">
            <tbody>
                <tr class="form-group">
                    <td> @Html.TextBoxFor(x => x.NewUserName, new { @class = "form-control", @placeholder = "Enter Username" })</td>
                </tr>
                <tr class="form-group">
                    <td> @Html.TextBoxFor(x => x.NewEmail, new { @class = "form-control", @placeholder = "Enter Email" })</td>
                </tr>
                <tr class="form-group">
                    <td> @Html.TextBoxFor(x => x.NewPassword, new { @class = "form-control", @placeholder = "Enter Password", @type = "password" })</td>
                </tr>
                <tr class="form-group">
                    <td> @Html.TextBoxFor(x => x.ConfirmPassword, new { @class = "form-control", @placeholder = "Re-enter Password", @type = "password" })</td>
                </tr>
            </tbody>
        </table>

        <div class="modal-footer">
            <div class="btn-group btn-group-lg">
                <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-success">Save</button>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">

    if (userEmail) {
        $("#NewEmail").val(userEmail);
        userEmail = undefined;
    }

    $("#SignupForm").on('submit',
        function (e) {
            SetLoadingDiv(true);
            e.preventDefault();

            $.ajax({
                url: "@Url.Action("Register")",
                method: "POST",
                data: $("#SignupForm").serialize(),
                success: function () {
                    location.href = "@Url.Action("Index", "Event")";
                },
                error: function (response) {
                    SetLoadingDiv(false);
                    if (response.status === 422) {
                        $(".modal-body").html(response.responseText);
                    }
                }

            });

        });
</script>

QuickEvents.Website.WebApp/Views/User/_RegisterSucess.cshtml
<h1>You have successfully registerd</h1>
<h2>Click activation email.</h2>